### ISSUE TITLE
Unable to authenticate the app!

### ISSUE THREAD

**Issue by sen3** [mrochon/b2ciefsetup#1]
Is it possible to add the instructions to how to set up Azure B2C and grant required permissions?

**Comment by mrochon** [comment]
Creating a B2C tenant is well [documented](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-tenant). Once the tenant exists you should be able to use this application to update the tenant for use with IEF custom policies. (Note that you do not need to use IEF with B2C. This [article ](https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-overview)explains when they are helpful). Use the same account you used to create the B2C tenant to run this application. Enter the name of the B2C tenant when starting the application. If this does not help, please provide details of what you are trying to do and what error you are seeing.

**Comment by sen3** [comment]
Hi,
  Thank you for the quick response. I wanted to set up the multitenant
scenario, that's why I am trying to use the custom policies.

 I follow the document and created the tenant. But, still no luck.  I am
getting the authorization failed exceptions.

I am including my manifest and screenshot of the configuration. Please let
me know, what is wrong.

PS: The hosted b2ciefsetup app is also not working.

Thanks,
Sen
,
[image: image.png]

**Comment by mrochon** [comment]
I didn't get the manifest or image. Email me at sailingrock at live.com if you want. The B2C Multitenant app is not working Setup seems OK.

**Comment by pacohams** [comment]
Hi mrochon , i hope you are well
i used the online https://b2ciefsetup.azurewebsites.net/ but i receveid the error, when i signing with the admin account of the b2c 
https://b2ciefsetup.azurewebsites.net/Error?msg=QUFEU1RTNTAwMjAyOiBVc2VyIGFjY291bnQgJ3tFbWFpbEhpZGRlbn0nIGZyb20gZXh0ZXJuYWwgaWRlbnRpdHkgcHJvdmlkZXIgJ2xpdmUuY29tJyBpcyBub3Qgc3VwcG9ydGVkIGZvciBBUEkgdmVyc2lvbiAnMi4wJy4gTWljcm9zb2Z0IGFjY291bnQgcGFzcy10aHJ1IHVzZXJzIGFuZCBndWVzdHMgYXJlIG5vdCBzdXBwb3J0ZWQgYnkgdGhlIHRlbmFudC1pbmRlcGVuZGVudCBlbmRwb2ludC4NClRyYWNlIElEOiBmMWZkYzIzNi04NTc1LTQ5YjMtYmVlYS1mZDg1ZDIxMTA1MDANCkNvcnJlbGF0aW9uIElEOiA0Y2JhOGMxOC1lODYyLTRmMzItODkyMC00ODNmNDE2YzY5YmUNClRpbWVzdGFtcDogMjAyMC0xMi0xOSAwNzo0MjozNlo

and in local runing i get this msg


{"IDW10104: Both client secret and client certificate cannot be null or whitespace, and only ONE must be included in the configuration of the web app when calling a web API. For instance, in the appsettings.json file. "}

i trieded to execute this steps (except facebook) and have the last error

https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started?tabs=applications

- Prerequisites

- Add signing and encryption keys
- Create the signing key
- Create the encryption key

- Register the IdentityExperienceFramework application
- Register the ProxyIdentityExperienceFramework application

i dont know whats is missing

**Comment by mrochon** [comment]
Base64 decoding of the error message says that you were trying to use an MSA account to login. That will not work. You need to use an AAD account, either your coprorate (if invited as guest into your B2C) or a local account created in your B2C (with xyz.onmicrosoft.com domain, where xyz is the name of your B2C). Hope this helps. Regards,

marius

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pacohams** [comment]
Nice Marius, thanks for your kindle answer,
 i changed the account type to my B2C xyz.onmicrosoft.com, but the next error is 

"{"IDW10104: Both client secret and client certificate cannot be null or whitespace, and only ONE must be included in the configuration of the web app when calling a web API. For instance, in the appsettings.json file. "}"

 i run in local and change appsettings.json parameters (Domain and ClientId)
The clientid is my previous web application
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "**Domain**": "xxx.onmicrosoft.com",
    "TenantId": "common",
    "**ClientId**": "07509905-ef39-4106-80de-b4685ad63a88",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc"
  },

i wondering is if i need change this parameter or i can use from your configuration


> Base64 decoding of the error message says that you were trying to use an MSA account to login. That will not work. You need to use an AAD account, either your coprorate (if invited as guest into your B2C) or a local account created in your B2C (with xyz.onmicrosoft.com domain, where xyz is the name of your B2C). Hope this helps. Regards, marius Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10 From: nomada2<mailto:notifications@github.com> Sent: Friday, December 18, 2020 11:48 PM To: mrochon/b2ciefsetup<mailto:b2ciefsetup@noreply.github.com> Cc: MariusR<mailto:sailingrock@live.com>; Comment<mailto:comment@noreply.github.com> Subject: Re: [mrochon/b2ciefsetup] Unable to authenticate the app! (#1) i used the online https://b2ciefsetup.azurewebsites.net/<https://na01.safelinks.protection.outlook.com/?

**Comment by mrochon** [comment]
The application uses OAuth2 Authz Code flow to get a token to Graph. Ith therefore needs a secret registered for it in AAD. Add one AAD App Registration and give it to your app in configuration. Note though that unless you need your own deployment of this application, you can simply [use the public version](https://b2ciefsetup.azurewebsites.net). That's a multi-tenant version of this app so you can use it from your tenant as well.

**Comment by pacohams** [comment]
Amazing, i resolved with the correct creation of the user
thanks so much
